version: "3.8"
services:
  webpage:
    image: ${DOCKERHUB_USERNAME}/${PROJECT_NAME}-web:0.0.1
    ports:
      - 80:80
  api:
    image: ${DOCKERHUB_USERNAME}/${PROJECT_NAME}-api:0.0.1
    secrets:
      - source: node-env
        target: /app/.env
    ports:
      - 8080:8080
    # `depends_on` tells Docker Compose to start the database before your application.
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15
    restart: always
    user: postgres
    volumes:
      # The `db-data` volume persists the database data between container restarts.
      - db-data:/var/lib/postgresql/data
    secrets:
      - db-password
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 3s
      timeout: 5s
      retries: 5
volumes:
  # The `db-data` volume persists the database data between container restarts.
  db-data:
secrets:
  # The `db-password` secret is used to set the database password.
  db-password:
    file: secrets/pg-password.txt
  node-env:
    file: secrets/node-env.txt
